ru-RU translation
Pomax/BezierInfo-2 pull request #294
Opened 2021-01-04 19:09 UTC by ra30r

Russian translation

2021-01-04 19:11 UTC, ra30r commented
** I've run start command to double check md syntax, but only pushed source files.

2021-01-06 17:20 UTC, Pomax requested changes
thank you! there's a few words that can still be translated

2021-01-06 17:20 UTC, Pomax commented on docs/chapters/control/content.ru-RU.md
> +\]
the `binomial~term`, `polynomial~term`, and `weight` under the undersets can also be translated (the `~` is a special LaTeX space in maths mode)

2021-01-06 17:20 UTC, Pomax commented on docs/chapters/control/content.ru-RU.md
> +<graphics-element title="Our cubic Bézier curve" src="../introduction/cubic.js"></graphics-element>
this title can be translated

2021-01-06 17:20 UTC, Pomax commented on docs/chapters/explanation/content.ru-RU.md
> +<graphics-element title="A (partial) circle: x=sin(t), y=cos(t)" src="./circle.js">
(title)

2021-01-06 17:21 UTC, Pomax commented on docs/chapters/explanation/content.ru-RU.md
> +  cubic &= BLUE[a] \cdot BLUE[a] \cdot BLUE[a] + BLUE[a] \cdot BLUE[a] \cdot RED[b] + BLUE[a] \cdot RED[b] \cdot RED[b] + RED[b] \cdot RED[b] \cdot RED[b]\\
"linear", "square", and "cubic" can be translated

2021-01-06 17:22 UTC, Pomax commented on docs/chapters/explanation/content.ru-RU.md
> +                \underset{polynomial~term}{\underbrace{(1-t)^{n-i} \cdot t^{i}}}
`binomial~term` and `polynomial~term` can be translated

2021-01-06 18:00 UTC, Pomax commented
For the conflicting files, you'll probably want to start working in a separate branch, instead of in `master`, so that you rebase your branch to master when necessary.

### making your code its own branch

You can turn the code that you have right now into a new branch called `translation`, without changing anything about the files, by using `git checkout -b translation`. You can now switch between which branch you want to work on by using `git checkout master`, to load the master branch, and `git checkout translation` to load the translation branch.

(Note that `checkout` means "checking out from your local copy of the repository files", not "checking out the code from github")

This means your master branch is now "free" to stay in sync with the one on this repository

### syncing your master branch

If you run `git checkout master` (after making sure you commit any code changes you might have of course!) you can sync it to the official master branch by first making sure you have the official remote available:

You can see a list of remotes by running `git remote`, which will probably show you this:

```bash
> git remote -v
origin  https://github.com/ra30r/BezierInfo-2 (fetch)
origin  https://github.com/ra30r/BezierInfo-2 (push)

```

this means git only knows about your own repo. To add this one as well, you can say:

```bash
> git remote add official https://github.com/Pomax/BezierInfo-2 
```

after this it should show the following:

```bash
> git remote -v
official https://github.com/Pomax/BezierInfo-2 (fetch)
official https://github.com/Pomax/BezierInfo-2 (push)
origin  https://github.com/ra30r/BezierInfo-2 (fetch)
origin  https://github.com/ra30r/BezierInfo-2 (push)

```

Which means any time you want to sync, you can now do:

```bash
> git checkout master
> git reset --hard
> git pull official master
```

That is, first we check out master, to make sure we have the right code loaded, then we reset it, so that we are certain there are no file changes, and then we pull the official branch state, which merges any commits not already merged in, in, so at the end of this process your `master` branch would be caught up.

The very very first time you do this, however, you can force-sync the master branch by "rebuilding" it from the official repo:

`> git checkout -B master official/master`

This throws away your local `master` branch, and then creates a new one with the same name, from the `official/master` branch instead. This is a useful command if you ever end up in a situation where you've been working in the master branch without realising it and you need to get the master branch back to the official state.

Also, should you ever need to remove a remote the command for that is `git remote rm nameofremote`.

### rebasing your working branch(es) so their PR doesn't conflict

In order to prevent PRs from having conflicts, you can rebase your branches so that they "start with" the current master branch, rather than whatever your local master branch was at the time you started your branch.

When you're on your not-master branch, first make sure any changes are captured in a commit (`git status` to verify there's nothing, but if there is, `git add ...` and `git commit -m "..."` to form a commit). Then, ensure your master branch is up to date (`git checkout master`, `git reset --hard`, `git pull official master`). Then the actual rebasing part:

```bash
> git checkout yourbranch
> git rebase -i master
```
this starts an interactive rebasing, where you get to say which commits you want to keep ("pick"), which commits should get merged into the previous commit instead of staying their own commit ("squash"), and which commits you don't even want to show up anymore (by deleting them entirely).

Now, unless there's a good reason to, just leave everything as is, and close the text editor that git opened for you. If it's a normal editor, easy enough, but if git opened `vi` it helps to know that you need to hit [esc] to tell it that you want the command prompt (which will show as `:` in the lower left) where you can then write `wq` and hit enter ("w"rite file, and then "q"uit).

https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request is a pretty decent guide that goes into all the details here.

once rebased, you can then push your now "properly synced branch" to github using the push mechanism:

```bash
> git push origin translation -f
```

where the only thing different is that `-f` flag, which means "force this push" because rebasing will have changes the commit history, and so git needs to be explicitly told that this is what you want.

2021-01-06 22:09 UTC, closed without merging