As requested
Pomax/BezierInfo-2 pull request #295
Opened 2021-01-06 22:36 UTC by ra30r

Pomax, 

Thank you for explicit instructions. I have played around with repos following your guides and accomplished moving 3 latest commits into separate branch; hard resetting / force pushing to your official master into my origin master and merging the above 2 to resolve conflicts. It has deleted original pull request at the point of force push. I'll pay attention to pulling from origin before making new pull request onto it. And I could also do a pull request from separate branch if thats anyhow beneficial or implied. Lastly — requested file changes (e.g. title name etc.) where incorporated before proceeding with all of this. Let me know of anything else that needs correction. Planning on translating more chapters later on this week.

2021-01-09 23:07 UTC, Pomax commented
Let me just say I massively appreciate you sticking with it to get these translations in. I remember how scary my first rebases were, and the fact that you've powered through them puts you above most folks!

2021-01-09 23:09 UTC, Pomax requested changes
two titles still need translating, but after that I think we can merge this in!

2021-01-09 23:09 UTC, Pomax commented on docs/chapters/explanation/content.ru-RU.md
> +<graphics-element title="A (partial) circle: x=sin(t), y=cos(t)" src="./circle.js">
this probably still needs a russian title

2021-01-09 23:09 UTC, Pomax commented on docs/chapters/weightcontrol/content.ru-RU.md
> +<graphics-element title="Our rational cubic Bézier curve" src="./rational.js">
`title` attribute

2021-01-10 18:03 UTC, ra30r commented
fixed titles, added another chapter

2021-01-10 19:24 UTC, Pomax approved these changes

2021-01-10 19:24 UTC, merged

2021-01-10 19:24 UTC, Pomax commented
nice, in it goes!

2021-01-10 19:59 UTC, Pomax commented
It looks like there were a few "double newlines" in the markdown, which throws off the conversion. To help us catch that in the future, I've added CI testing for pull requests, and I've filed https://github.com/Pomax/BezierInfo-2/issues/296 as a task to add automatic markdown reformatting during the build step (similar to `prettier` for the js)

2021-01-11 19:04 UTC, ra30r commented
> It looks like there were a few "double newlines" in the markdown, which throws off the conversion. To help us catch that in the future, I've added CI testing for pull requests, and I've filed #296 as a task to add automatic markdown reformatting during the build step (similar to `prettier` for the js)

Sorry about that, didn't catch it since using regular text editor for spell check highlights. CI testing is nice, though. Sort of fancy too — installing tex-live on the go..  the only version I found for mac so far was like 6 gb.

2021-01-13 17:27 UTC, Pomax commented
I think you can use `brew` to only install the parts of TeX Live that you need, too, but I just did a full texlive install on my own mac (I mostly work on Windows, but I have a mac for additional testing) as I stuck a fairly large SSD in it so space is not an issue.

2021-01-13 17:29 UTC, Pomax commented
ah, no. It looks like for mac, the preferred solution is [mactex](https://www.tug.org/mactex/)