[zh-CN] Added translation of Chapter "matrixsplit"
Pomax/BezierInfo-2 pull request #342
Opened 2022-01-28 04:55 UTC by yarusome

I found this book really illustrative with a flat learning curve and it's useful for programmers and mathematicians alike. I plan to translate the book into simplified Chinese this year with overhaul for previously translated chapters toward the end since there are many show-stoppers in the existing translation, i.e. "primer" → "底漆" (paint applied at the bottom layer), "implementing" → "实习" (internship).

However, I'm not a programmer by profession and this is my first time using GitHub, so there might be wrong actions done inadvertently.

2022-01-29 20:09 UTC, Pomax commented
More than happy to take translations and corrections - all the translations are community contributions, so if there are typos, or even just bad characters, I'll never know, myself =D

2022-02-16 02:37 UTC, yarusome commented
I hope it was not too serious and you could get well soon. I've resumed translation since last week, too. Btw, is there any pending procedure I have to complete to get the workflow approved?

2022-02-27 19:06 UTC, Pomax requested changes
just one small change request

2022-02-27 19:06 UTC, Pomax commented on docs/chapters/matrixsplit/content.zh-CN.md
> +以上变形可行是因为[*M · M<sup>-1</sup>*]为单位矩阵。这有点像在计算中让某项乘以x/x——不改变函数本身，却可以将函数改写为更好处理的形式或者得到不同的分解。类似地将上式中的矩阵左乘以[*M · M<sup>-1</sup>*]不会影响整个式子，却可以将矩阵序列[*something · M*]变为[*M · something*]，而这至关重要——如果知道了[*M<sup>
it probably makes sense to translate "something" to the Chinese equivalent here, too.

2022-02-27 19:07 UTC, Pomax commented
I finally have a working arm and hand again, so I will doing the outstanding pull request reviews. Apologies that it took so long.

2022-03-24 03:01 UTC, closed without merging